### ISSUE TITLE
MigrationsMap.net website out of scope

### ISSUE THREAD

**Issue by claudep** [madewulf/MigrationsMap.net#2]
Hey @madewulf,

Looks like the domain name MigrationsMap.net is now owned by some chinese person/firm. Is the former website content still available somewhere? If it's the case, would be great to at least indicate the new location in this repository description.

**Comment by madewulf** [comment]
The site is still available here: http://madewulf.github.io/MigrationsMap.net/#/USA/arrivals but the data is severely outdated, which is the reason I didn't renew the domain anymore.

**Comment by claudep** [comment]
Thanks for the new link! However, you still link to the "Chinese" site in the About section of the repository home page. What about updating that link? Same issue in the README.

**Comment by madewulf** [comment]
I updated the links. Thanks for the feedback.
